Complete homework Lesson 3
eugene-okulik/quality-test-pro pull request #10
Opened 2023-06-30 13:46 UTC by sergey211

2023-07-02 07:39 UTC, eugene-okulik requested changes
В целом хорошо.  
Но проверку на внимательность с кортежем не прошел )))  
Это исправь, а остальное - рекомендации.

2023-07-02 07:39 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson3/task1.py
> +print('')
Если хочешь просто распечатать пустую строку, то можно без кавычек, вот так:
```python
print()
```

2023-07-02 07:39 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson3/task1.py
> +dict1['(\'i am a tuple\',)'] = '(\'uno, due, tres\')'
Нужно было добавить элемент не с ключом `"('i am a tuple',)"`, а с ключом `('i am a tuple',)`  
В твоем варианте ключ - строка. В нужном варианте ключ - кортеж

2023-07-02 07:39 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson3/task1.py
> +my_dict['list'] = list1
Можно было не сохранять список в переменную, а все преобразования делать непосредственно на месте, тогда не нужно было бы писать дополнительный код. Т.е. не делать сначала 
```python
list1 = my_dict.get('list')
```
а сразу делать
```python
my_dict['list'].append(6)
```
Ведь, по сути, словарь и есть набор переменных, с каждой из которых можно сразу брать и работать. Бывают сложные структуры внутри словаря и тогда есть смысл сохранять в переменную, а потом возвращать в словарь. Но здесь структура простая.

2023-07-02 10:54 UTC, sergey211 commented on homework/sergey_svetlichny/lesson3/task1.py
> +print('')
ага, спасибо, подправил

2023-07-02 10:55 UTC, sergey211 commented on homework/sergey_svetlichny/lesson3/task1.py
> +dict1['(\'i am a tuple\',)'] = '(\'uno, due, tres\')'
да, у меня поначалу все элементы словаря были в кавычках) потом везде исправил, а тут нет, исправляю)

2023-07-02 10:57 UTC, sergey211 commented on homework/sergey_svetlichny/lesson3/task1.py
> +my_dict['list'] = list1
Сразу не понял (и не нашел) как обращаться внутрь списков / кортежей которые в словаре, потому выносил их в отдельные переменные, сейчас буду понимать, так действительно проще спасибо!

2023-07-06 06:36 UTC, eugene-okulik approved these changes

2023-07-06 06:36 UTC, merged