sergey: homework 4 completed
eugene-okulik/quality-test-pro pull request #14
Opened 2023-07-05 11:24 UTC by sergey211

2023-07-06 07:00 UTC, eugene-okulik requested changes
Все работает как ожидается, но в первом задании местами перемудрил.

2023-07-06 07:00 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson4/task1.py
> +    str1 = my_list[i]
Вот эти две строчки делаются намного проще:
```python
for str1 in my_list:
```
И всё. В переменную `str1` попадает каждый элемент списка.

2023-07-06 07:00 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson4/task1.py
> +    text_new += my_list_new[i]
А вот эти три строчки можно заменить на
```python
text_new = ' '.join(my_list_new)
```

2023-07-06 07:00 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson4/task1.py
> +    if my_list[i][-1] == ',':
У тебя `my_list[i]` хранится в переменной `str1`, а ты все равно обращаешься к `my_list[i]`

2023-07-06 07:00 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson4/task1.py
> +       'dignissim vitae libero'
Здесь ты сделал перенос так что между `at,` и `dignissim` нет пробела.  
Вообще, переносы с помощью `\` не рекомендуются PEP-8

2023-07-06 07:00 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson4/task1.py
> +        my_list_new.append(str2 + 'ing ')
Этот `elif` повторяет первый `if` и никогда не отрабатывает. Можешь попробовать его убрать - результат не поменяется

2023-07-06 07:00 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson4/task2.py
> +    print('Wow! You won!')
Круто, что использовал такую конструкцию!

2023-07-06 07:00 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson4/task3.py
> +        print(i)
Вложенные условия здесь очень упрощают код. Очень аккуратно получилось.

2023-07-07 08:36 UTC, sergey211 commented on homework/sergey_svetlichny/lesson4/task1.py
> +    str1 = my_list[i]
исправил, спасибо!

2023-07-07 08:38 UTC, sergey211 commented on homework/sergey_svetlichny/lesson4/task1.py
> +    text_new += my_list_new[i]
интересный метод, почитал, исправил, благодарю!

2023-07-07 08:38 UTC, sergey211 commented on homework/sergey_svetlichny/lesson4/task1.py
> +    if my_list[i][-1] == ',':
да, скорректировал

2023-07-07 08:46 UTC, sergey211 commented on homework/sergey_svetlichny/lesson4/task1.py
> +       'dignissim vitae libero'
нагуглил только такой способ, перечитал по ссылке из предыдущих домашек:
"Предпочтительный способ переноса длинных строк является использование подразумеваемых продолжений строк Python внутри круглых, квадратных и фигурных скобок. Длинные строки могут быть разбиты на несколько строк, обернутые в скобки. Это предпочтительнее использования обратной косой черты для продолжения строки." 
Но у нас ведь тут нету скобок, как можно перенести тут без косой черты?

2023-07-07 08:48 UTC, sergey211 commented on homework/sergey_svetlichny/lesson4/task1.py
> +        my_list_new.append(str2 + 'ing ')
Этот код отрабатывает, он обрабатывает ситуацию из предыдущего комментария, где между at, и dignissim нет пробела. Я думал это очередная хитрость задания, а оказалось что я сам удалил этот пробел)

2023-07-07 08:52 UTC, sergey211 commented on homework/sergey_svetlichny/lesson4/task2.py
> +    print('Wow! You won!')
Спасибо) как-то по книге изучения питона делал похожую игру, только там было чуть сложнее, 
https://github.com/sergey211/PythonSimpleGames/blob/main/game1%20-%20guess%20the%20number.py - вот тут лежит

2023-07-08 07:11 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson4/task1.py
> +       'dignissim vitae libero'
Эти скобки нужно добавить ))  
Берешь весь текст в скобки - и переноси себе сколько влезет, никакого слеша не нужно будет

2023-07-08 07:13 UTC, eugene-okulik approved these changes

2023-07-08 07:13 UTC, merged