sergey: homework 5 completed
eugene-okulik/quality-test-pro pull request #15
Opened 2023-07-05 13:10 UTC by sergey211

2023-07-06 07:17 UTC, eugene-okulik requested changes

2023-07-06 07:17 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson5/task1.py
> +print(d)
_Это коментарий ко всему файлу._
Результат правильный, но ты по несколько раз пишешь один и тот же код.  
Одно из главных правил программирования гласит "Не повторяй себя"  
Подскажу: ты в коде 3 раза пишешь код, который умножает одно число на другое и два раза пишешь код по распечатыванию практически одинаковых строк.

2023-07-06 07:17 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson5/task2.py
> +        print(x)
Ожидаемый результат:

> III
> lovelovelovelove

Твой результат:

> I
> I
> I
> love
> love
> love
> love
> love

2023-07-07 09:19 UTC, sergey211 commented on homework/sergey_svetlichny/lesson5/task1.py
> +print(d)
исправил, да, стало гораздо красивее и интереснее, спасибо!

2023-07-07 09:19 UTC, sergey211 commented on homework/sergey_svetlichny/lesson5/task2.py
> +        print(x)
исправил

2023-07-08 07:16 UTC, eugene-okulik requested changes

2023-07-08 07:16 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson5/task1.py
> +print(d)
Теперь ты два раза пишешь код, где умножаешь одно число на другое.

2023-07-08 07:26 UTC, sergey211 commented on homework/sergey_svetlichny/lesson5/task1.py
> +print(d)
"а х b"   и    "с х е" ?

2023-07-08 21:54 UTC, sergey211 commented on homework/sergey_svetlichny/lesson5/task1.py
> +print(d)
добавил функцию умножения

2023-07-15 07:40 UTC, eugene-okulik approved these changes
Всё хорошо, но нет предела совершенству )))

2023-07-15 07:40 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson5/task1.py
> +print(d)
Я что-то упускаю, или переменная `d` просто хранит пустую строку, а потом она распечатывается?

2023-07-15 07:40 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson5/task2.py
> +        print(x, end='')
Этот `for` можно было заменить на 
```python
print(x * words[x])
```
А если пробегаться по словрю с помощью words.items(), то и еще проще

2023-07-15 07:40 UTC, merged