sergey: homework 6 completed
eugene-okulik/quality-test-pro pull request #20
Opened 2023-07-12 20:57 UTC by sergey211

2023-07-16 07:26 UTC, eugene-okulik requested changes
В первом хорошо выкрутился, но можно было еще проще сделать.  

Второе - на занятии обсуждали, что правильнее сделать так, чтобы функция `fibon` просто занималась тем, что генерировала ряд чисел фибоначчи, а уже вне этой функции управлять тем сколько чисел мы из нее получим и какие из них мы хотим распечатать.  
И еще, вижу что в функции ты все числа накапливаешь в списке `my_list`. Это тоже неправильно. Фишка генератора в том, что всё, что он генерирует, он сразу отдает и не накапливает внутри себя, т.к. когда там будет миллиард чисел, комп может и загнуться. Подсказка: тебе нужно накапливать только 2 последних числа. Можно это сделать списком из двух элементов или просто двумя переменными.

2023-07-16 07:26 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson6/task1.py
> +b = randint(0, 1)
Вот в этом месте можно было сразу зарандомить `True` или `False` и тогда не нужно было бы писать логику по вычислению переменной `bonus`. Сделать это можно было так:
```python
bonus = random.choice((True, False))
```

2023-07-17 11:32 UTC, sergey211 commented on homework/sergey_svetlichny/lesson6/task1.py
> +b = randint(0, 1)
интересно! исправил, спасибо

2023-07-17 11:32 UTC, sergey211 commented on homework/sergey_svetlichny/lesson6/task1.py
> +b = randint(0, 1)
интересно! исправил, спасибо

2023-07-17 12:14 UTC, sergey211 commented
Исправил и с Фибоначчи, теперь лимит туда передается извне, и в списке теперь только 2 последних числа последовательности

2023-07-20 07:10 UTC, eugene-okulik approved these changes
Не буду тебя дальше мучать. По заданию с фибоначчи: одна из целей создания функций - сделать код более читаемым. Сейчас у тебя есть функция `fibon`, в которой реализована вся логика приложения, а цикл внизу только распечатывает результат. То есть твоя функция и генерирует числа и выбирает из них нужные. Но лучше, чтобы функция выполняла только одно действие. Внутри функции очень неудобно разбираться что же в ней происходит. Ну и когда мы пытаемся всунуть в одну функцию несколько действий у нас и появляется необходимость создавать глобальные переменные.
Весь твой код можно превратить вот в такой более понятный и даже более короткий:
```python
my_count = [0, 1, 2, 3, 4, 5, 200, 1000, 100000]
lastsymb = 100005

def fibon(lasts):
    my_list = [0, 1]
    for i in range(0, lasts):
        fib = my_list[0] + my_list[1]
        my_list.append(fib)
        my_list.pop(0)
        yield fib


print("Выводим результат: ")
for count, fib in enumerate(fibon(lastsymb)):
    if count in my_count:
        print("Число Фибоначчи c порядковым номером " + str(count) + " является : " + str(fib))
```
Ты видишь, что я в список `my_count` добавил еще 0, 1, 2, 3, 4 - с помощью этого я проверил правильно ли генерируются числа фибоначчи. И выходит, что неправильно. Начало твоих чисел такое:
```
1, 2, 3, 5,...
```
А должно быть 
```
0, 1, 1, 2, 3, 5,...
```
Если будут вопросы - приходи

2023-07-20 07:10 UTC, merged