sergey: homework 7 completed
eugene-okulik/quality-test-pro pull request #25
Opened 2023-07-17 10:48 UTC by sergey211

Не смог сделать отфильтровку высоких температур через map , но сделал через фильтр, выкладываю решение через filter + попытки решений через map для обсуждения.

2023-07-20 08:00 UTC, eugene-okulik requested changes
Прикольно, что ты сделал определение разделителя.  
Подчеркну еще раз - использование глобальных переменных считается плохой практикой. На деле, существует 0,001% вероятность, что глобальная переменная в коде действительно необходима. А у тебя из целых три. Здесь точно можно обойтись без глобальных переменных.

В задании я по ошибке написал про `map`, там действительно нужен `filter`. Ну, заодно попрактиковался в `map` и понял что он может или не может.

2023-07-20 08:00 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson7/task1.py
> +            my_list: list[str] = date1.split(parsesymbols[x])
Для чего ты превращаешь это в список? Ты этим списком потом не пользуешься.

2023-07-20 08:00 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson7/task1.py
> +    for x in range(0, len(parsesymbols)):
Такой for легко заменяется на 
```python
for symbol in parsesymbols
```

2023-07-20 15:03 UTC, sergey211 commented on homework/sergey_svetlichny/lesson7/task1.py
> +            my_list: list[str] = date1.split(parsesymbols[x])
я my_list  передавал в другую функцию, где хотел еще считать кол-во символов в введенном году, но потом забил на это, и по факту этот список то передавал, но не использовал) удалил, спасибо!

2023-07-20 15:06 UTC, sergey211 commented
Глобальные переменные - то чем я раньше часто пользовался, сейчас понимаю, что можно все решать по-другому, переделаю все без их использования, спасибо!

2023-07-20 22:03 UTC, sergey211 commented on homework/sergey_svetlichny/lesson7/task1.py
Переделал очень много, не понял как лучше делать передачу из одной функции в другую, поэтому сделал вот таким тройным вложением: checklist(parsedate(input_date())) С одной стороны сложно, а с другой вроде и просто, но хотелось бы понять как было бы правильнее) У меня вводимая  дата отдается из функции в функцию один раз, и в parsedate пытался передать ее снова, но мне нужно еще и передать разделитель. Попробовал отдать обе эти переменные через ретурн, и это получилось. Но на вход в checklist пришел tuple , распарсил его на входе и получил то что нужно) Но как-то сложно-замудрённо получилось. Как проще было?)

2023-07-21 06:15 UTC, eugene-okulik requested changes

2023-07-21 06:15 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson7/task1.py
По сути, две первые функции являются вспомогательными функциями для функции `checklist`, поэтому их можно вне функции и не запускать, а сделать так
```python
def checklist():
    date = input_date()
    separator = parsedate(date)
    python_date = datetime.datetime.strptime(date, '%d' + separator + '%m' + separator + '%Y')
    print('Данная дата в формате питона выглядит так: ')
    print(python_date)
    return True
```
Ну и функция `parsedate` тогда должна возвращать только разделитель.

2023-07-21 06:15 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson7/task1.py
И сейчас у тебя не очень логичное поведение:
```
А ну-ка введи-ка какую-нибудь дату: 31!12!2023
Не введен разделитель
```
Но разделитель ведь введён.

2023-07-21 06:15 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson7/task1.py
> +    python_date = datetime.datetime.strptime(date, '%d' + separator + '%m' + separator + '%Y')
А вот эту строчку лучше делать форматированием, а не конкатенацией:
```python
f'%d{separator}%m{separator}%Y'
```

2023-07-21 13:14 UTC, sergey211 commented on homework/sergey_svetlichny/lesson7/task1.py
> +    python_date = datetime.datetime.strptime(date, '%d' + separator + '%m' + separator + '%Y')
Спасибо, все поправил! Старое решение (замудрёное) оставил закоменченным, для истории)

2023-07-22 07:05 UTC, eugene-okulik approved these changes

2023-07-22 07:05 UTC, merged