sergey: homework 8, questions
eugene-okulik/quality-test-pro pull request #26
Opened 2023-07-19 00:33 UTC by sergey211

Отправил код сюда, чтобы было наглядно и меня тут вопросы по задачам:

1. у меня есть декоратор, есть функция, декоратор присылает мне знак, 
каким образом передать его в саму функцию?

2. я обрабатываю список построчно в цикле, внутри которого сначала убираю знак р после цены
и делю строку на 2 слова. Во втором действии создаю словарь из этих 2 слов преобразуя одно в инт.
Как понимаю, в генераторе необходимо указывать одну строку, но тут одна строка без другой не имеет
смысла: ведь тогда придется дважды бегать по списку и это нерационально. Что тут нужно придумать?

2023-07-20 09:04 UTC, eugene-okulik requested changes

2023-07-20 09:04 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson8/task1.py
> +            return "+"
Здесь вместо ретурна нужно делать вызов функции с правильным оператором. Если нужно больше деталей - спрашивай

2023-07-20 09:04 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson8/task1.py
> +            return "+"
В остальном, всё праильно. Только ретурны заменить на вызов функции

2023-07-20 09:04 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson8/task2.py
> +    array = line.rstrip((line[-1])).split(" ")
Когда сплит по пробелу, в скобках можно ничего не указывать - это дефолтное поведение

2023-07-20 09:04 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson8/task2.py
> +for line in lines:
Весь этот for можно записать одной строкой. По сути, в этом и есть задание, но нужно поломать голову как это сделать ))

2023-07-20 09:04 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson8/task2.py
> +for line in lines:
Небольшая подсказка.  
Эта строка будет начинаться так:
```python
new_dict = {k: v for k, v in ....
```

2023-07-20 22:44 UTC, sergey211 commented on homework/sergey_svetlichny/lesson8/task1.py
> +            return "+"
return func(a, b, '+')
понял, спасибо)

2023-07-21 06:18 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson8/task1.py
> +            return "+"
Не совсем. Просто
```python
func(a, b, '+')
```

2023-07-22 07:18 UTC, eugene-okulik reviewed
С декоратором ок. Будешь второе пытаться сделать одной строкой? Ну, для упрощения, можно двумя.

2023-07-26 13:58 UTC, sergey211 commented
Было непросто, но зато очень многое понял/повторил/закрепил, и наконец справился. Возможно можно было как-то и проще сделать, но очень хотелось одной строкой, в этой строке у меня и зип, и рстрип,  и срезы и лямбда функция. Комментарии сознательно оставил, чтобы на будущее понимать, как пришел к окончательному решению. Долго разбирался со срезами, но это было полезно. И к последнему чему пришел это была лямбда функция, чтобы убрать "р" в цене, можно было это решить без лямбды, но одной строкой?

2023-07-28 06:17 UTC, eugene-okulik approved these changes
То как ты решил - это вариант отличный. Ну и дополнительно ты попрактиковался с зипами и лямбдами. В них разобраться - хорошее дело.  
Так, чисто для расширения кругозора, вот еще одно решение:  
```python
new_dict = {k: v for k, v in [line.rstrip((line[-1])).split() for line in PRICE_LIST.splitlines()]}
```  
Можем на занятии рассмотреть подробно как к этому прийти.

2023-07-28 06:17 UTC, merged