sergey: homework 9 completed
eugene-okulik/quality-test-pro pull request #28
Opened 2023-07-20 09:58 UTC by sergey211

2023-07-21 06:47 UTC, eugene-okulik requested changes

2023-07-21 06:47 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson9/task1.py
> +    def __init__(self, page_material, is_text_present, name, author, pages_qty, reserved):
Получается, что для каждой книги нужно будет заполнить из бумаги ли она, есть ли в ней текст, но небумажных книг без текста не существует. Это будут свойства, которые одинаковы у всех книг и не нужно их задавать при создании каждого экземпляра.

2023-07-21 06:47 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson9/task1.py
> +Book.isbn = ''
Что здесь имелось ввиду?

2023-07-21 06:47 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson9/task1.py
> +book_3.isbn = '978-5-9287-3204-2'
Ты назначаешь параметр книги, которого в классе не описано

2023-07-21 06:47 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson9/task1.py
> +book_4 = Book('бумага', True, 'Подземелья черного замка', 'Дмитрий Браславский', 342, True)
Ты помечаешь книгу как зарезервированную во время создания, хотя в задании

> После создания пометьте одну книгу как зарезервированную.

2023-07-21 06:47 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson9/task1.py
> +    is_task_present: bool
В питоне не нужно объявлять переменные до их создания

2023-07-21 06:47 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson9/task1.py
> +          ', предмет: ' + x.subject, ', класс: ' + str(x.group), x.is_reserved())
Вместо конкатенации лучше пользоваться форматированием `f-string`

2023-07-22 04:41 UTC, sergey211 commented on homework/sergey_svetlichny/lesson9/task1.py
> +    is_task_present: bool
имеется ввиду что надо сразу указать какое-либо значение?
    is_text_present = True
    author: ''
    pages_qty: 0
Так?

2023-07-22 04:53 UTC, sergey211 commented on homework/sergey_svetlichny/lesson9/task1.py
> +Book.isbn = ''
перенес внутрь класса

2023-07-22 07:20 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson9/task1.py
> +    is_task_present: bool
ага, вроде того

2023-07-22 07:23 UTC, eugene-okulik approved these changes

2023-07-22 07:23 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson9/task1.py
> +    name = ''
Если какие-то свойства заполняются при инициализации (в методе `__init__`), то можно их изначально не задавать. А задать здесь только те, которые будут одинаковыми для всех экземпляров

2023-07-22 07:23 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson9/task1.py
> +            return ''
Кстати, в прошлый раз не отметил - клево, что ты вот это сделал методом внутри класса. Очень удобно при распечатке потом

2023-07-22 07:23 UTC, merged