lesson2 half of homework
eugene-okulik/quality-test-pro pull request #6
Opened 2023-06-25 00:12 UTC by sergey211

2023-06-25 08:26 UTC, eugene-okulik requested changes
Почини все, на что ругается Lint и то, что я указал в коменте

2023-06-25 08:26 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson2/task3.py
> +a = int(input())
Можно было сразу одной строкой сделать `a = int(input('input a '))`

2023-06-26 06:32 UTC, eugene-okulik approved these changes
Всё отлично, но с делением на 1 я не понял. Но задание все равно на питон, а не на математику ))

2023-06-26 06:32 UTC, eugene-okulik commented on homework/sergey_svetlichny/lesson2/task2.py
> +print('x - y/1 +xy = ' + str(x - y / 1 + x * y))
А деление на 1 для чего?

2023-06-26 06:32 UTC, merged

2023-06-29 12:30 UTC, sergey211 commented on homework/sergey_svetlichny/lesson2/task2.py
> +print('x - y/1 +xy = ' + str(x - y / 1 + x * y))
"Получить x − y / 1 + xy"

видимо я не правильно понял это задание)